-- CREATE TABLE users
-- (
--     id         VARCHAR(256) PRIMARY KEY,
--     password   VARCHAR(2048) NOT NULL,
--     role       VARCHAR(32)   NOT NULL DEFAULT 'ROLE_USER',
--     first_name VARCHAR(64)   NOT NULL,
--     last_name  VARCHAR(64)   NOT NULL,
--     enabled    BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP,
--     updated_at TIMESTAMP
-- );